### ISSUE TITLE
touch ups

### ISSUE THREAD

**Issue by jordanddunn** [CosmoCMS/Cosmo#224]
- [x] fix nav on newmanium to work with the select dropdowns in place
- [x] hide view more button when there's no more images to view
- [x] when you hit backspace in the page editor it unformats the text incorrectly instead of leaving the applied type treatment to it (i.e., if you hit backspace on a paragraph it will double in size). This is not the case on client site.
- [x] logo img for pendant is loading after everything else and is noticeably slow (also it's not loading from amazon)
- [x] use the pendant single post blog block for the blog overview page
- [x] profile photo is missing/can't upload for pendant
- [x] blocks aren't saving for pendant (the footer in particular)
- [x] images are corrupted within the media manager on pendant
- [x] resizing images to retina increased the size from 262kb to 1.1mb
- [x] leave/enter putting you halfway down the page instead of shooting to the top of the page
- [x] header on this page http://cosmocms.org/how-to-create-a-theme-for-cosmo isn't styling correctly
- [x] when you update your profile image, it should update immediately on the sidebar area instead of requiring a refresh
- [x] profile image should auto pull 320px

**Comment by nickleus** [comment]
@jordanddunn upload button for profile image doesn't do anything onclick
