### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /core/app/Cosmo.class.php on line 922

### ISSUE THREAD

**Issue by sweimer** [CosmoCMS/Cosmo#287]
Followed install directions on shared server.  Entered details on install.php page.  Got this Parse Error.  Any ideas?

![01062015cosmocms](https://cloud.githubusercontent.com/assets/1145769/5640945/ea05d3ce-95fb-11e4-990f-7554fc8a8973.PNG)

**Comment by James-Dunn** [comment]
This issue should be fixed in version beta 3, released today.
