### ISSUE TITLE
Windows permissions app/core/autoload

### ISSUE THREAD

**Issue by nahuelsgk** [CosmoCMS/Cosmo#290]
Hello!
I just was trying to install it on windows and error rose up. 
Error: File core/app/autoload.php permissions are not set to 777. Please change them and refresh. 
I think the main problem, is that a file can't be a 777 permission on Windows Systems.
On the core/html/install.html i'vs just change the line 10 just to bypass it.

**Comment by James-Dunn** [comment]
Yeah, that's just a warning message to the user, but doesn't stop you from installing. Do you know the equivalent on a Windows machine so we can check the file either has 777 permissions or (windows equivalent)?

**Comment by nahuelsgk** [comment]
Hum... I think may you can not get this permission on windows. I think, maybe the right thing is just to check is able to write.
I couldn't continue installation. I had to change /core/html/install.html line 10 to that line
<p class="error" ng-if="autoloadPermissions!=='0666'">

But i think is because another thing I've found. On my developing work machine my MySQL user is root without password. And as the password input was empty, the writer put into the file autoload.php:
$password = 'undefined';
I think this is because for the JS, the empty value is "undefined" and when it was sent to the server, the PHP red "undefined" as string.
To make work the installation I had to put an extra line on the install.php just to test it and finally work:
    if ($password == 'undefined') $password = '';

I will continue exploring the cms.

**Comment by nahuelsgk** [comment]
The install.php in Linux does another error. If I put autoload to 777, the fopen do a 
"Warning: fopen(core/app/autoload.php) [function.fopen]: failed to open stream: S’ha denegat el permís in /opt/lampp/htdocs/Cosmo/install.php on line 35"
In catalan, mean that have no permissions. Maybe something with PHP version? This is a 5.3.8
Quite strange because don't write nothing at all.

**Comment by James-Dunn** [comment]
I think I fixed the 'undefined' issue, will be up in beta.4. Will work on the permissions issue next weekend.

**Comment by Sogl** [comment]
>Error: File core/app/autoload.php permissions are not set to 777. Please change them and refresh. 
I think the main problem, is that a file can't be a 777 permission on Windows Systems.

>But i think is because another thing I've found. On my developing work machine my MySQL user is root without password. And as the password input was empty, the writer put into the file autoload.php:
$password = 'undefined';

Confirm the both problems. Dear developers, please fix it.

**Comment by James-Dunn** [comment]
Fixed the permissions issue too. Now it should just check if the file is writeable. Will make it into beta 4.
