### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by Sogl** [CosmoCMS/Cosmo#294]
Hi!

Do you have plans to add multilanguage support? I mean switching languages in frontend.
Can't found anything about it in "Docs".

**Comment by jordanddunn** [comment]
We are working on implementing the ability to switch languages that the community translates for cosmo. It will be in the beta4 version coming out soon.

**Comment by Sogl** [comment]
This means that I will be able to link the different language versions to the same material, right?

**Comment by James-Dunn** [comment]
Right. There will be a drop down to select a language, and translate all Cosmo material. Although we will need people to translate the text into different language.

**Comment by Sogl** [comment]
>Although we will need people to translate the text into different language.
I can help with Russian language (my native). 

What files you need to translate?

**Comment by James-Dunn** [comment]
That would be great if you could translate it into Russian. If you could duplicate the file https://github.com/CosmoCMS/Cosmo/blob/master/core/languages/en.json and replace the right phrases (the left side of the colon stays the same) then rename it ru.json.

Then we could test this feature out on a real translation instead of just dummy data.

**Comment by Sogl** [comment]
Done.
https://github.com/CosmoCMS/Cosmo/pull/297

You must check initial translation file for duplicates:
```
"toolbar_insert_table": "Insert Table",
"toolbar_paste_table": "Paste Table",
"toolbar_table_head": "Table Head",
"toolbar_table_head": "Table Head",
```

Is it normal? "paste" and "insert" have a similar meaning I think.

**Comment by James-Dunn** [comment]
Thanks a lot. I merged it and will try to get it working this weekend. "Insert table" creates one from scratch. "Paste table" lets you copy/paste from a CSV file.

The capitalization was just a design choice for some areas. Shouldn't matter.

**Comment by James-Dunn** [comment]
Check the latest release, it should have Russian in the settings as well as a few fixes
