### ISSUE TITLE
Installation challenges

### ISSUE THREAD

**Issue by mikkelking** [CosmoCMS/Cosmo#298]
Hi,
I got Cosmo up and running, after a bit of trial and error:
1) pre-requisites: mod-rewrite - all i got was a blank screen and it was re-directed to /error

2) if I leave the database password as blank, it saved 'undefined' as the password, which doesn't work - Now I know that my database password should not be blank, please don't give me a hard time on that:)

3) comments table, I added the following 
    alter table cosmo_comments add path varchar(255);
    alter table cosmo_comments add timestamp varchar(30);
Not sure if the column widths are right, but it allowed me to add comments after that

Cheers

Mike

**Comment by James-Dunn** [comment]
Thanks for the feedback. We'll add 1 to the list. 2 will be fixed in beta v4. I'll have to look into the comments table.

**Comment by mikkelking** [comment]
Great, thanks.

BTW Cosmo looks like a great idea, I hope you can keep going with it. I'd be happy to lend a hand where I can (if I have the time), even if it's just doing some testing for you
