### ISSUE TITLE
Cosmo polish translation

### ISSUE THREAD

**Issue by kosmaa** [CosmoCMS/Cosmo#305]
Based on en.json file that was mentionned in #294, I've made a translation to polish: 
https://www.dropbox.com/s/5c13coeje7vmptj/pl.json?dl=0
I hope I will enjoy Cosmo some day when I will surpass all installation issues I'm having (look my comment in #302).

**Comment by jordanddunn** [comment]
Thank you very much for the translation! @James-Dunn will take a look at your issue on install, I'm sorry you've had trouble with it.
