### ISSUE TITLE
Gallery placeholder image needs to show in the gallery

### ISSUE THREAD

**Issue by jordanddunn** [CosmoCMS/Cosmo#311]
Need to have the placeholder image added into the gallery instead of it being blank. When a user adds an image into the gallery, it needs to remove the placeholder from the overview area even before saving  etc...

**Comment by James-Dunn** [comment]
Why?

**Comment by jordanddunn** [comment]
Have the placeholder image so it doesn't look broken, and it would remove so the user doesn't think that it will appear in their gallery once they put photos in.
