### ISSUE TITLE
Language not showing as being active

### ISSUE THREAD

**Issue by jordanddunn** [CosmoCMS/Cosmo#313]
If you select another language (russian/polish) and return to settings, it shows english as being selected instead of the currently selected language

**Comment by James-Dunn** [comment]
Unable to duplicate

**Comment by jordanddunn** [comment]
Go to settings, select russian, go out of settings and back in, it will show english as being active (see below)

![screen shot 2015-04-26 at 12 24 51 pm](https://cloud.githubusercontent.com/assets/5115944/7338111/3f61ff46-ec0f-11e4-83f4-f4e196e49cc2.png)

**Comment by jordanddunn** [comment]
Ah nvm, issue was related to not saving before hand but changing the preview ahead of time.
