### ISSUE TITLE
Tag suggestions

### ISSUE THREAD

**Issue by jordanddunn** [CosmoCMS/Cosmo#318]
tag suggestions don't seem to be working on the sidebar when typing in for page info

**Comment by James-Dunn** [comment]
Unable to duplicate

**Comment by jordanddunn** [comment]
On the edit page (page details) page, it's no longer showing the suggested tags

![screen shot 2015-04-26 at 12 25 39 pm](https://cloud.githubusercontent.com/assets/5115944/7338113/58d0a874-ec0f-11e4-8f2b-dce25d942b68.png)

**Comment by James-Dunn** [comment]
Should be fixed with latest pull request. Can view on Builtwith.. Needs styling
