### ISSUE TITLE
logo/favicon to pull from gallery

### ISSUE THREAD

**Issue by jordanddunn** [CosmoCMS/Cosmo#334]
- [x] logo and favicon need to pull from the gallery, currently they're trying to pull from the modal

- [x] updating image in profile needs to pull from updated gallery reference

**Comment by James-Dunn** [comment]
update the path, search for the current one, e.g. /gallery/ and replace it with the new directory path

**Comment by jordanddunn** [comment]
It's pulling things like this 

$scope.addProfilePhoto = function(){
        ngDialog.open({ template: 'core/html/modal.html', data: angular.toJson({ id: 'profile' }) });
    };

along with things like this for the banner images

if(Users.admin) {
                // Double click image to edit
                elm.on('dblclick', function(){
                   ngDialog.open({ template: 'core/html/modal.html', data: angular.toJson({ id: attrs.csBgImage }) });
                });

                // Update page when another image is chosen
                scope.$on('choseFile', function(event, data){
                    if(data.id === attrs.csBgImage){
                        Page.extras[attrs.csBgImage] = data;
                        elm.css('background-image', 'url('+ data.src +')');
                    }
                });
            }


I think this is tied into the whole #306
