### ISSUE TITLE
http://www.XXXX.XXX/api/content?url=%2Findex.php

### ISSUE THREAD

**Issue by JoeFirmament** [CosmoCMS/Cosmo#357]
When I access the index.php after the installation ,the result always point to a 404 error . I found that   two urls  (http://www.xxxx.xxx/api/content?url=%2Findex.php and http://www.xxxx.xxx/api/content?url=%2Ferror) cause the error, but I didn't find the snip about 2 urls in the code .I love Cosmo CMS and all u doing here .Thx for ur help .

**Comment by James-Dunn** [comment]
Do you have ModRewrite enabled on your server? Might be a .htaccess problem with not routing the url correctly.

**Comment by JoeFirmament** [comment]
@James-Dunn ,Thx for ur replay . ModRewrite is enable and keep default .htaccess file in the folder.
May be I should to  figured out how  the .htaccess works ,but I have searched the code about "api/content", but can't find one.

**Comment by JoeFirmament** [comment]
@James-Dunn  @jordanddunn  ，thx for ur help . I've figure it out .  All bcos my  mistake on mypart, 
some wrong with the httpd.conf.Thx again, I love Cosmo very much !
