### ISSUE TITLE
More Hooks than two?

### ISSUE THREAD

**Issue by Aerobraking** [CosmoCMS/Cosmo#384]
Hello,

I'm interested in writing a module for Cosmo, that manipulates the content of a site, that is opened. 

But there isn't a hook yet for this content, as far as I can see. What are your plans on adding more hooks, especially the one for the content, before it is displayed in the browser.

Cheers,
Konnie

**Comment by James-Dunn** [comment]
Sure. I can add a hook/callback for content to the next release.

**Comment by Aerobraking** [comment]
Great!

My goal is to write a module that implements animations by switching from one site to another, therefore I need to add additional identifier to the html tags.
