### ISSUE TITLE
Multilingual Sites ?

### ISSUE THREAD

**Issue by daslicht** [CosmoCMS/Cosmo#390]
How would we create Multilingual Sites (and slugs) with it ?
I have noticed that we get a blank page without js enabled , how do we get properly index by search engines ?

**Comment by James-Dunn** [comment]
We use https://angular-translate.github.io/ to change the admin language. You can check that site to see how you would add new languages to the front end of the site.

**Comment by daslicht** [comment]
I am talking about multilingual content and slugs

**Comment by James-Dunn** [comment]
Right, but it's the same process if you want translations on the front end. You'll need separate json files with the language files, and a function to switch between the languages. 

You should be able to create content/URLs in any language, but I haven't tested it.

To answer your earlier question, the search engines are able to index dynamic sites now. As a fall-back, the body text and most of the content is put into the HTML on the first page load.
